// LaTeX source generator for resume + cover letter.
//
// Builds self-contained .tex from the parsed CV (CVData from cv_parse.ts). The output:
//   - Compiles with vanilla `pdflatex` on any TeX Live install (no fontspec, no
//     charter, no minted, no exotic packages).
//   - Uses Computer Modern Roman — ubiquitous, ATS-clean, prints to letter paper.
//   - Tight but generous spacing tuned to stay within a 1-letter page for typical
//     content AND to handle long content without producing overfull \hbox warnings.
//   - Real \section / \begin{itemize} structure — no images, no text boxes.
//
// scanForVisaLeakage() must be called on the returned string by the caller before
// writing to disk; the rail applies to every output format, not just the PDF.

import { parseCV, type CVData, type ExperienceItem, type ProjectItem, type EducationItem, type SkillCategory } from './cv_parse.js';

// ── Public API ──────────────────────────────────────────────────────────────

export interface CoverFields {
  /** Plain prose cover body (250–350 words). Paragraph-broken on blank lines. */
  body:     string;
  /** Company name as it should appear under the date. */
  company:  string;
  /** Optional company location appended after the company name. */
  location: string;
}

/** Build the resume .tex from cv.md + profile.yml. */
export function buildResumeTex(): string {
  const cv = parseCV();
  return resumeDocument(cv);
}

/** Build the cover letter .tex. Uses identity from cv.md + the prose body. */
export function buildCoverTex(args: CoverFields): string {
  const cv = parseCV();
  return coverDocument(cv, args);
}

// ── Resume document ─────────────────────────────────────────────────────────

function resumeDocument(cv: CVData): string {
  const lines: string[] = [];
  lines.push(PREAMBLE_RESUME);
  lines.push('\\begin{document}');
  lines.push('');
  lines.push(header(cv));
  lines.push('');

  if (cv.summary?.trim()) {
    lines.push('\\section*{Summary}');
    lines.push(escapeLatex(cv.summary.trim()));
    lines.push('');
  }
  if (cv.skills?.length) {
    lines.push('\\section*{Skills}');
    lines.push(skillsSection(cv.skills));
    lines.push('');
  }
  if (cv.experiences?.length) {
    lines.push('\\section*{Experience}');
    for (const e of cv.experiences) lines.push(experienceBlock(e));
    lines.push('');
  }
  if (cv.projects?.length) {
    lines.push('\\section*{Projects}');
    for (const p of cv.projects) lines.push(projectBlock(p));
    lines.push('');
  }
  if (cv.education?.length) {
    lines.push('\\section*{Education}');
    for (const e of cv.education) lines.push(educationBlock(e));
    lines.push('');
  }

  lines.push('\\end{document}');
  return lines.join('\n');
}

const PREAMBLE_RESUME = String.raw`% Auto-generated by job_ops-mcp. Pure pdflatex --- no fontspec, no exotic packages.
% Compile with: pdflatex resume.tex
\documentclass[letterpaper,11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.7in,top=0.65in,bottom=0.65in]{geometry}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{titlesec}
\usepackage[hidelinks]{hyperref}

\definecolor{accent}{HTML}{145374}

% Tight, ATS-clean sections. Section title is sans-bold-uppercase with an accent rule.
\titleformat{\section}
  {\normalfont\large\bfseries\color{accent}}
  {}{0pt}{}[\vspace{-6pt}\titlerule\vspace{2pt}]
\titlespacing*{\section}{0pt}{10pt}{4pt}

% Tight lists: minimal vertical waste so a real resume fits without overfull boxes.
\setlist[itemize]{
  leftmargin=*,
  topsep=2pt,
  partopsep=0pt,
  parsep=1pt,
  itemsep=2pt,
  label=\textbullet,
}

% No paragraph indent; sober paragraph spacing.
\setlength{\parindent}{0pt}
\setlength{\parskip}{2pt}

% Generous line-breaking budget so long bullets stretch instead of overflowing.
\sloppy
\setlength{\emergencystretch}{3em}
\tolerance=2000

\pagestyle{empty}
\raggedright
`;

function header(cv: CVData): string {
  const contact: string[] = [];
  if (cv.location)      contact.push(escapeLatex(cv.location));
  if (cv.email)         contact.push(escapeLatex(cv.email));
  if (cv.phone)         contact.push(escapeLatex(cv.phone));
  const links: string[] = [];
  if (cv.linkedin_url)  links.push(`\\href{${escapeUrl(cv.linkedin_url)}}{${escapeLatex(cv.linkedin_display || cv.linkedin_url)}}`);
  if (cv.portfolio_url) links.push(`\\href{${escapeUrl(cv.portfolio_url)}}{${escapeLatex(cv.portfolio_display || cv.portfolio_url)}}`);

  const lines: string[] = [];
  lines.push(`{\\huge\\bfseries ${escapeLatex(cv.name || 'Candidate')}}`);
  if (contact.length) lines.push(`\\\\[2pt]\n{\\small ${contact.join(' \\quad ')}}`);
  if (links.length)   lines.push(`\\\\[1pt]\n{\\small ${links.join(' \\quad ')}}`);
  return lines.join('\n');
}

function skillsSection(skills: SkillCategory[]): string {
  return skills.map(s => `\\textbf{${escapeLatex(s.category)}:} ${escapeLatex(s.items)}\\\\`).join('\n');
}

function experienceBlock(e: ExperienceItem): string {
  const right = e.period ? `\\hfill {\\small\\itshape ${escapeLatex(e.period)}}` : '';
  const meta  = [e.role, e.location].filter(Boolean).map(escapeLatex).join(' \\textemdash{} ');
  const out: string[] = [];
  out.push(`\\textbf{${escapeLatex(e.company)}} ${right}`);
  if (meta) out.push(`\\\\\n{\\small ${meta}}`);
  if (e.bullets?.length) {
    out.push('');
    out.push('\\begin{itemize}');
    for (const b of e.bullets) out.push(`  \\item ${escapeLatex(b)}`);
    out.push('\\end{itemize}');
  }
  out.push('');
  return out.join('\n');
}

function projectBlock(p: ProjectItem): string {
  const badge = p.badge ? ` {\\small(${escapeLatex(p.badge)})}` : '';
  const tech  = p.tech  ? `\\\\\n{\\footnotesize\\textit{${escapeLatex(p.tech)}}}` : '';
  return `\\textbf{${escapeLatex(p.title)}}${badge} \\textemdash{} ${escapeLatex(p.description)}${tech}\\\\[2pt]`;
}

function educationBlock(e: EducationItem): string {
  const year = e.year ? ` \\hfill {\\small\\itshape ${escapeLatex(e.year)}}` : '';
  const org  = e.org  ? `, ${escapeLatex(e.org)}` : '';
  const desc = e.desc ? `\\\\\n{\\small ${escapeLatex(e.desc)}}` : '';
  return `\\textbf{${escapeLatex(e.title)}}${org}${year}${desc}\\\\[2pt]`;
}

// ── Cover letter document ───────────────────────────────────────────────────

function coverDocument(cv: CVData, args: CoverFields): string {
  const paras = args.body
    .split(/\n{2,}/)
    .map(p => p.trim())
    .filter(Boolean)
    .map(escapeLatex);

  const contact: string[] = [];
  if (cv.location) contact.push(escapeLatex(cv.location));
  if (cv.email)    contact.push(escapeLatex(cv.email));
  if (cv.phone)    contact.push(escapeLatex(cv.phone));

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const companyLine = [args.company, args.location].filter(Boolean).join(', ');

  return [
    PREAMBLE_COVER,
    '\\begin{document}',
    '',
    `{\\large\\bfseries ${escapeLatex(cv.name || 'Candidate')}}\\\\`,
    `{\\small ${contact.join(' \\quad ')}}`,
    '',
    `\\vspace{1.2em}`,
    escapeLatex(today),
    '',
    `\\vspace{1em}`,
    'Hiring Team\\\\',
    escapeLatex(companyLine || args.company || 'Hiring Team'),
    '',
    '\\vspace{1em}',
    'Dear Hiring Manager,',
    '',
    ...paras.map(p => `${p}\n`),
    '\\vspace{1em}',
    'Best regards,\\\\',
    escapeLatex(cv.name || 'Candidate'),
    '',
    '\\end{document}',
  ].join('\n');
}

const PREAMBLE_COVER = String.raw`% Auto-generated cover letter by job_ops-mcp. Compile with: pdflatex cover.tex
\documentclass[letterpaper,11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{parskip}
\usepackage[hidelinks]{hyperref}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.6em}
\sloppy
\setlength{\emergencystretch}{3em}
\tolerance=2000
\pagestyle{empty}
\raggedright
`;

// ── LaTeX escaping ──────────────────────────────────────────────────────────

const LATEX_SPECIALS: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&':  '\\&',
  '%':  '\\%',
  '$':  '\\$',
  '#':  '\\#',
  '_':  '\\_',
  '{':  '\\{',
  '}':  '\\}',
  '~':  '\\textasciitilde{}',
  '^':  '\\textasciicircum{}',
};

const SPECIAL_RE = /[\\&%$#_{}~^]/g;

/** Escape every LaTeX special. Order matters: \ must be first or it double-escapes. */
export function escapeLatex(s: string | null | undefined): string {
  if (s == null) return '';
  // First pass: escape backslashes via a sentinel so the regex below doesn't see them.
  return String(s).replace(SPECIAL_RE, ch => LATEX_SPECIALS[ch] ?? ch);
}

/** URL escaping for \href — only escape #, %, & (which are URL-safe but LaTeX-special). */
function escapeUrl(u: string): string {
  return u.replace(/[%#&]/g, ch => '\\' + ch);
}
